# Generated by Django 4.1.4 on 2023-01-02 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.post'),
        ),
    ]
