# Generated by Django 4.1.4 on 2023-01-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_author_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3),
        ),
    ]
